(function () {
    var componentClass = 'paginator-component',
        unpaginatedClass = 'paginator-unpaginated',
        modelClass = 'model',
        viewClass = 'view',
        watchClass = 'watch',
        pageClass = 'page',
        pageBlockClass = 'page-block',
        pageAddedClass = 'page-added',
        pageDeletedClass = 'page-deleted',
        contentClass = 'content',
        headerClass = 'header',
        footerClass = 'footer',
        marginClass = 'margin',
        parentDataAttrName = 'parent',
        terminalClass = '-terminal';

    /**
     * Converts a class string to a CSS selector.
     * @param {string} classString The class string.
     * @returns {string} The selector string.
     */
    function toClassSelector(classString) {
        return '.' + classString.split(' ').filter(function (string) { return string.trim().length > 0 }).join('.');
    }

    /**
     * Class for the options for the paginator.
     * @param {object} rawOpts The raw options data.
     * @constructor
     */
    function PaginatorOptions(rawOpts) {
        return rawOpts;
    }

    /**
     * Class for the container of contents on a page.
     * @param {string} klass The class name of the main HTML element generated by the component.
     * @param {PaginatorOptions} opts The options of the paginator.
     * @constructor
     */
    function PaginatorPageContent(klass, opts) {
        var self = this,
            page;

        /**
         * Creates the elements of the component.
         */
        function createElement() {
            self.$el = self.$el || $('<div>').addClass(klass);
            self.$margin = self.$margin = $('<div>').addClass(marginClass);

            self.$el.append(self.$margin);
        }

        /**
         * Appends a content to this component.
         * @param {jQuery} $el The element to append.
         */
        self.append = function append($el) {
            self.$margin.append($el);
        };

        self.clear = function clear() {
            self.$margin.html('');
        };

        /**
         * Mounts this component to a parent component.
         * @param {object} parent The parent component.
         */
        self.mountTo = function mountTo(parent) {
            if (page === parent) {
                return;
            }

            page = parent;
            page.$el.append(self.$el);
        };

        /**
         * Gets the content blocks of this component.
         * @returns {jQuery} The content blocks of this component.
         */
        self.getBlocks = function getBlocks() {
            return self.$margin.children();
        };

        createElement();
    }

    /**
     * Class for the page that is to be rendered in the paginator.
     * @param {PaginatorOptions} opts The options of the paginator.
     * @constructor
     */
    function PaginatorPage(opts) {
        var self = this,
            view;

        self.header = new PaginatorPageContent(headerClass, opts);
        self.content = new PaginatorPageContent(contentClass, opts);
        self.footer = new PaginatorPageContent(footerClass, opts);

        /**
         * Creates the elements of the component.
         */
        function createElement() {
            self.$el = self.$el || $('<div>').addClass(pageClass);
            self.$el
                .append(self.header.$el)
                .append(self.content.$el)
                .append(self.footer.$el);
        }

        /**
         * Gets the content height of the page.
         * @returns {number} The content height of the page.
         */
        function getContentHeight() {
            var $header = self.$el.find(toClassSelector(headerClass)),
                $footer = self.$el.find(toClassSelector(footerClass)),
                $margin = self.content.$margin,
                topHeight = Math.max($header.length > 0 ? $header.height() : 0, parseInt($margin.css('margin-top'))),
                bottomHeight = Math.max($footer.length > 0 ? $footer.height() : 0, parseInt($margin.css('margin-bottom')));

            return self.$el.height() - topHeight - bottomHeight;
        }

        /**
         * Gets the lower boundary of the page.
         * @returns {number} The lower boundary of the page.
         */
        function getContentLowerBoundary() {
            return parseInt(self.content.$el.css('margin-top')) + getContentHeight();
        }

        /**
         * Determines if the page has elements that can trigger page breaks.
         * @returns {boolean}
         */
        self.hasBreaks = function hasBreaks() {
            return self.getOverflowBlocks().length > 0;
        };

        /**
         * Gets the elements that overflow the content area of the page.
         * @returns {jQuery} The elements.
         */
        self.getOverflowBlocks = function getOverflowBlocks() {
            return self.content.getBlocks()
                .filter(function () {
                    var $block = $(this),
                        position = $block.position().top,
                        height = $block.height();

                    return position + height > getContentLowerBoundary();
                });
        };

        /**
         * Mounts the component to a parent.
         * @param {object} parent The component
         */
        self.mountTo = function mountTo(parent) {
            if (view === parent) {
                return;
            }

            view = parent;
            view.$el.append(self.$el);
        };

        createElement();
    }

    /**
     * Class for the renderer of the paginator.
     * @param {PaginatorOptions} opts
     * @constructor
     */
    function PaginatorRenderer(opts) {
        var self = this,
            model,
            view,
            firstPage = new PaginatorPage(opts);

        function writeHeader(page, i) {
            var $header,
                hasTerminal = model.hasTerminalBlockContainer(headerClass),
                headerIndex = model.getIndexForPage(headerClass, i);

            page.header.clear();

            model
                .getBlocks(headerClass)(headerIndex)
                .each(function () {
                    var $block = $(this),
                        $blockParent;

                    $header = $block.clone(true, true);

                    if ($block.parents(toClassSelector(pageDeletedClass)).length > 0) {
                        return;
                    }

                    $blockParent = $block.parent();

                    $blockParent
                        .addClass('block-parent')
                        .attr('data-order', 0);

                    $header
                        .data(parentDataAttrName, $blockParent)
                        .removeClass(pageBlockClass)
                        .addClass(pageAddedClass);

                    page.header.append($header);
                });

            page.content.$margin.css('margin-top', page.$el.find(toClassSelector(headerClass)).height());
        }

        /**
         * Writes the appropriate headers and the footers of the page.
         */
        function writePageComponents() {
            view.pages.forEach(function (page, i) {
                writeHeader(page, i);
            });
        }

        /**
         * Writes the content of the page.
         */
        function writeContent() {
            model
                .getBlocks('content')
                .each(function () {
                    var $block = $(this),
                        $blockParent;

                    if ($block.parents(toClassSelector(pageDeletedClass)).length > 0) {
                        return;
                    }

                    $blockParent = $block.parent();

                    $blockParent
                        .addClass('block-parent')
                        .attr('data-order', 0);

                    $block
                        .data(parentDataAttrName, $blockParent)
                        .removeClass(pageBlockClass)
                        .addClass(pageAddedClass);

                    firstPage.content.append($block);
                });
        }

        /**
         * Sets the ordering of each block rendered in the view.
         */
        function setOrder() {
            model
                .getBlocks('content')
                .each(function (i) {
                    $(this).attr('data-order', i);
                });
        }

        /**
         * Checks the view for deleted blocks and performs the appropriate actions.
         */
        function checkDeletedBlocks() {
            view
                .getBlocks('content')
                .each(function () {
                    var $block = $(this),
                        $blockParent,
                        isParentDeleted;

                    $blockParent = $block.data(parentDataAttrName);

                    isParentDeleted = !$blockParent ||
                            $blockParent.hasClass(pageDeletedClass) ||
                            $blockParent.parents(toClassSelector(pageDeletedClass)).length > 0;

                    if (!isParentDeleted) {
                        return;
                    }

                    $block.remove();
                });
        }

        /**
         * Inserts a page for new content.
         * @param {{blocks:jQuery,pageIndex:number}} content The content.
         */
        function insertPageForContent(content) {
            var newPage = new PaginatorPage(opts);

            content.blocks.each(function () {
                newPage.content.append($(this));
            });

            view.pages.slice(content.pageIndex + 1).forEach(function (page) {
                newPage.content.append(page.content.getBlocks());
            });

            view.addPage(newPage);
        }

        /**
         * Gets the content of the first page that has a break.
         * @returns {{blocks:jQuery,pageIndex:number}} The content to insert.
         */
        function getFirstPageWithBreak() {
            var pageToBreak = null;

            view.pages.forEach(function (page, i) {
                if (!page.hasBreaks() || pageToBreak !== null) {
                    return;
                }

                // Get the first page to have page breaks.
                pageToBreak = {
                    pageIndex: i,
                    blocks: page.getOverflowBlocks()
                };
            });

            return pageToBreak;
        }

        /**
         * Performs page breaks among the view's pages.
         * @returns {boolean} A value that determines if the renderer performed page breaks, which is used to repeat this method.
         */
        function performPageBreaks() {
            var pageToBreak = getFirstPageWithBreak();

            if (pageToBreak === null) {
                return false;
            }

            insertPageForContent(pageToBreak);
            return true;
        }

        /**
         * Performs all page breaks when the renderer detects at least one page that has a page break.
         */
        function performAllPageBreaks() {
            var hasPerformedPageBreaks;

            do {
                hasPerformedPageBreaks = performPageBreaks();
            } while (hasPerformedPageBreaks);
        }

        /**
         * Renders the content.
         */
        function renderContent() {
            checkDeletedBlocks();
            writeContent();
            setOrder();
            performAllPageBreaks();
            writePageComponents();
            //performAllPageBreaks();
            //writePageComponents();
        }

        self.render = function render() {
            if (view.pages.length < 1) {
                view.addPage(firstPage);
            }

            renderContent();
        };

        self.mountTo = function mountTo(parent) {
            model = parent.model;
            view = parent.view;

            self.render();
        };
    }

    /**
     * Class for the model of the paginator.
     * @param {PaginatorOptions} opts The options of the paginator.
     * @constructor
     */
    function PaginatorModel(opts) {
        var self = this,
            paginator;

        function createElement() {
            self.$el = self.$el || $('<div>').addClass(modelClass);
            if (!!self.$watch) {
                return;
            }
            self.$watch = self.$watch || $('<div>').addClass(watchClass);
            self.$el.append(self.$watch);
        }

        function getBlockContainers(klass, isTerminal) {
            return self.$watch.children(toClassSelector(!!isTerminal ? klass + ' ' + terminalClass : klass));
        }

        function getCount(klass) {
            return getBlockContainers(klass).length;
        }

        function getIndexForTerminalBlockContainer(klass, pageNumber) {
            var $currBlockContainer = getBlockContainers(klass).eq(0),
                i, j, hasHeaderTerminalClass, hasFooterTerminalClass;

            for (
                i = 0,
                j = 0;

                i < paginator.view.pages.length;

                i++,
                j = (j + 1) % getCount(headerClass),
                $currBlockContainer = $currBlockContainer.next()
            ) {
                if (!$currBlockContainer) {
                    $currBlockContainer = getBlockContainers(klass).eq(0);
                }

                hasHeaderTerminalClass = klass === headerClass && $currBlockContainer.hasClass(terminalClass);
                hasFooterTerminalClass = klass === footerClass && $currBlockContainer.hasClass(terminalClass);

                if (hasHeaderTerminalClass && pageNumber > 0 ||
                    hasFooterTerminalClass && pageNumber < paginator.view.getPageCount() - 1) {
                    ++j;
                }

                if (i === pageNumber ||
                    hasHeaderTerminalClass && pageNumber === 0 ||
                    hasFooterTerminalClass && pageNumber === paginator.view.getPageCount() - 1) {
                    return j;
                }
            }
        }

        self.hasTerminalBlockContainer = function hasTerminalBlockContainer(klass) {
            return getBlockContainers(klass, true).length > 0;
        };

        self.getIndexForPage = function getIndexForPage(klass, pageNumber) {
            if (!self.hasTerminalBlockContainer(klass)) {
                return pageNumber % getCount(klass);
            }

            return getIndexForTerminalBlockContainer(klass, pageNumber);
        };

        self.getBlocks = function getBlocks(klass) {
            switch (klass) {
                case headerClass:
                case footerClass:
                    return function (i) {
                        var $blockContainer = getBlockContainers(klass).eq(i),

                            isTerminal = $blockContainer.hasClass(terminalClass),
                            $blocks = $blockContainer.find(toClassSelector(pageBlockClass));

                        return isTerminal ?
                            $blocks.addClass(terminalClass) :
                            $blocks.removeClass(terminalClass);
                    };
                default:
                    break;
            }

            return getBlockContainers(klass).find(toClassSelector(pageBlockClass));
        };

        self.getOrderedBlocks = function getOrderedBlocks(klass) {
            return getBlockContainers(klass).find('[data-order]');
        };

        self.mountTo = function mountTo(parent) {
            if (paginator === parent) {
                return;
            }

            paginator = parent;
            paginator.$el.append(self.$el);
        };

        createElement();
    }

    /**
     * Class for the view of the paginator.
     * @param {PaginatorOptions} opts The options of the paginator.
     * @constructor
     */
    function PaginatorView(opts) {
        var self = this,
            paginator;

        self.pages = self.pages || [];

        function createElement() {
            self.$el = self.$el || $('<div>').addClass(viewClass);
        }

        function addToPageList(page, i) {
            if (isNaN(i) || i === null) {
                self.pages.push(page);
                return;
            }

            self.pages.splice(i, 0, page);
        }

        self.getPageCount = function getPageCount() {
            return self.pages.length;
        };

        self.getBlocks = function getBlocks(klass) {
            return self.$el
                .find(toClassSelector(klass))
                .children(toClassSelector(marginClass))
                .children();
        };

        self.addPage = function addPage(page, i) {
            addToPageList(page, i);
            page.mountTo(self);
            return page;
        };

        self.mountTo = function mountTo(parent) {
            paginator = parent;
            paginator.$el.append(self.$el);
        };

        createElement();
    }

    /**
     * Class for the paginator.
     * @param {object} opts The options of the paginator.
     * @constructor
     */
    function Paginator(opts) {
        var self = this,
            modelObserver,
            pub;

        opts = new PaginatorOptions(opts);
        self.model = new PaginatorModel(opts);
        self.view = new PaginatorView(opts);
        self.renderer = new PaginatorRenderer(opts);
        modelObserver = new MutationObserver(render);

        function render() {
            self.renderer.render();
        }

        function bindToElement($el) {
            if (!!self.$el) {
                self.$el.removeClass(componentClass);
            }
            self.$el = $el;
            if (self.$el.hasClass(componentClass)) {
                return;
            }
            self.$el
                .addClass(componentClass)
                .removeClass(unpaginatedClass);
        }

        function createModel() {
            self.model.mountTo(self);

            self.model.$watch.append(
                self
                    .$el
                    .children()
                    .filter(function () {
                        var $el = $(this);

                        return !(
                            $el.hasClass(modelClass) ||
                            $el.hasClass(viewClass) ||
                            $el.hasClass(watchClass)
                        );
                    })
            );
        }

        function createView() {
            self.view.mountTo(self);
        }

        function createRenderer() {
            self.renderer.mountTo(self);
        }

        function observeModel() {
            modelObserver
                .observe(self.model.$watch[0], {
                    childList: true,
                    attributes: true,
                    characterData: true,
                    subtree: true
                });
        }

        pub = {
            refresh: function doRender() {
                render();
            }
        };

        self.bindTo = function bindTo($el) {
            bindToElement($el);
            createModel();
            createView();
            createRenderer();
            observeModel();
            $el.data('paginator', pub);
        };
    }

    $.fn.paginate = function paginate(opts) {
        new Paginator(opts).bindTo(this);
    };
})();
